language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls nose --use-mirrors
script:
  - "python setup.py install"
  - "nosetests tests --with-coverage --cover-package=mailpile"
after_success:
  - "coveralls"
before_install:
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-i686.tar.bz2
  - tar -xf phantomjs-1.9.2-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mvphantomjs-1.9.2-linux-i686 /usr/local/phantomjs
